# This file configures the overall theme of the Chatbot; Changing values here will immediately reflect in the Streamlit cloud hosted version

[theme]
base="light"
primaryColor="#147c5c"
backgroundColor="#050505"
secondaryBackgroundColor="#f0f0f0"
textColor="#e3e1e1"
font="sans serif"
